# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-27 09:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_article_auser'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='article_c',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.Article', verbose_name='文章'),
        ),
    ]
